[package]
name = "aethel-tauri"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aethel-core = { path = "../aethel-core" }
aethel-storage = { path = "../aethel-storage" }
aethel-auth = { path = "../aethel-auth" }
aethel-manifest = { path = "../aethel-manifest" }
aethel-launch = { path = "../aethel-launch" }
aethel-java = { path = "../aethel-java" }
aethel-modding = { path = "../aethel-modding" }
specta = { workspace = true }
specta-typescript = "0.0.9"
tauri-specta = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
minisign-verify = { workspace = true }
semver = { workspace = true }
uuid = { workspace = true }
discord-rpc-client = { workspace = true }
tracing = { workspace = true }
open = { workspace = true }
flate2 = { workspace = true }
base64 = { workspace = true }
zip = { workspace = true }
walkdir = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
