[package]
name = "aethel-modding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aethel-core = { path = "../aethel-core" }
tokio = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
