[package]
name = "aethel-auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aethel-core = { path = "../aethel-core" }
md-5 = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
keyring = { workspace = true }
aes-gcm = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["sync", "time", "net", "io-util", "rt"] }
urlencoding = { workspace = true }
open = { workspace = true }
specta = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }