
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getLauncherVersion() : Promise<string> {
    return await TAURI_INVOKE("get_launcher_version");
},
async getOfflineUuid(username: string) : Promise<string> {
    return await TAURI_INVOKE("get_offline_uuid", { username });
},
async getInstances() : Promise<Result<Instance[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_instances") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createInstance(name: string, gameVersion: string, loader: string, loaderVersion: string | null, ramOverrideMb: number | null) : Promise<Result<Instance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_instance", { name, gameVersion, loader, loaderVersion, ramOverrideMb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMinecraftVersions() : Promise<Result<MinecraftVersionEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_minecraft_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteInstance(instanceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_instance", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLaunchReceipt(gameVersion: string, username: string) : Promise<Result<LaunchReceipt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_launch_receipt", { gameVersion, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchWithActiveIdentity(gameVersion: string | null, memoryMaxMb: number | null, javaPath: string | null, gcPreset: string | null) : Promise<Result<LaunchReceipt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_with_active_identity", { gameVersion, memoryMaxMb, javaPath, gcPreset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchInstance(instanceId: string, gameVersion: string | null, memoryMaxMb: number | null, javaPath: string | null, gcPreset: string | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_instance", { instanceId, gameVersion, memoryMaxMb, javaPath, gcPreset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectSystemJava() : Promise<Result<JavaInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_system_java") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadJre(major: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_jre", { major }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstalledRuntimes() : Promise<Result<InstalledRuntime[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installed_runtimes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadRuntime(major: number, provider: string | null) : Promise<Result<InstalledRuntime, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_runtime", { major, provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRuntime(major: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_runtime", { major }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecommendedJava(gameVersion: string) : Promise<number> {
    return await TAURI_INVOKE("get_recommended_java", { gameVersion });
},
async resolveJavaForInstance(gameVersion: string, manualPath: string | null, provider: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_java_for_instance", { gameVersion, manualPath, provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadCrashToMclogs(instanceId: string | null, logContent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_crash_to_mclogs", { instanceId, logContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeCrashLog(exitCode: number | null, logContent: string) : Promise<Result<CrashReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_crash_log", { exitCode, logContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loginMicrosoft() : Promise<Result<AccountMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_microsoft") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loginOffline(username: string) : Promise<Result<AccountMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_offline", { username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loginAuthlib(serverUrl: string, username: string) : Promise<Result<AccountMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_authlib", { serverUrl, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAccounts() : Promise<Result<AccountMetadata[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveAccount() : Promise<Result<AccountMetadata | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveAccount(uuid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_account", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logout(uuid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchMods(query: string, gameVersion: string | null, loader: string | null) : Promise<Result<ModSearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_mods", { query, gameVersion, loader }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModVersions(projectId: string, gameVersion: string | null, loader: string | null) : Promise<Result<ModVersion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mod_versions", { projectId, gameVersion, loader }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installMod(instanceId: string, versionId: string) : Promise<Result<ResolutionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_mod", { instanceId, versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installModloader(instanceId: string, loader: string, loaderVersion: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_modloader", { instanceId, loader, loaderVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uninstallModloader(instanceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_modloader", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModloaderVersions(loader: string, gameVersion: string) : Promise<Result<ModloaderVersion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_modloader_versions", { loader, gameVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInstalledMods(instanceId: string) : Promise<Result<InstalledMod[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_installed_mods", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleMod(instanceId: string, fileName: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_mod", { instanceId, fileName, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMod(instanceId: string, fileName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mod", { instanceId, fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModIcon(instanceId: string, fileName: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mod_icon", { instanceId, fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkModUpdates(instanceId: string) : Promise<Result<ModUpdate[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_mod_updates", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdates(channel: string | null) : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadAndInstallUpdate(channel: string | null, downloadUrl: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_and_install_update", { channel, downloadUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importModpack(filePath: string, instanceName: string | null) : Promise<Result<Instance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_modpack", { filePath, instanceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportModpack(instanceId: string, outputPath: string, name: string, version: string, summary: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_modpack", { instanceId, outputPath, name, version, summary }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportInstanceBackup(instanceId: string, outputPath: string, includeSaves: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_instance_backup", { instanceId, outputPath, includeSaves }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importInstanceBackup(filePath: string) : Promise<Result<Instance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_instance_backup", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGlobalSettings() : Promise<Result<GlobalSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_global_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGlobalSettings(settings: GlobalSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_global_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstanceSettings(instanceId: string) : Promise<Result<InstanceSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_instance_settings", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateInstanceSettings(instanceId: string, settings: InstanceSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_instance_settings", { instanceId, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEffectiveInstanceSettings(instanceId: string) : Promise<Result<EffectiveInstanceSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_effective_instance_settings", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDiscordRpcEnabled(enabled: boolean, locale: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_discord_rpc_enabled", { enabled, locale }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDiscordRpcActivity(locale: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_discord_rpc_activity", { locale }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openInstanceFolder(instanceId: string, subfolder: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_instance_folder", { instanceId, subfolder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateInstanceName(instanceId: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_instance_name", { instanceId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateInstanceIcon(instanceId: string, iconPath: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_instance_icon", { instanceId, iconPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstanceResourcepacks(instanceId: string) : Promise<Result<ResourcePackEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_instance_resourcepacks", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleInstanceResourcepack(instanceId: string, packName: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_instance_resourcepack", { instanceId, packName, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstanceShaderpacks(instanceId: string) : Promise<Result<ShaderPackEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_instance_shaderpacks", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setInstanceActiveShaderpack(instanceId: string, shaderName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_instance_active_shaderpack", { instanceId, shaderName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstanceWorlds(instanceId: string) : Promise<Result<WorldEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_instance_worlds", { instanceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectModpack(filePath: string) : Promise<Result<ModpackInspectResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_modpack", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchModpacks(query: string, provider: string, loader: string | null, gameVersion: string | null, limit: number | null) : Promise<Result<ModpackSearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_modpacks", { query, provider, loader, gameVersion, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installOnlineModpack(provider: string, projectId: string, versionId: string | null, instanceName: string) : Promise<Result<Instance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_online_modpack", { provider, projectId, versionId, instanceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickFileDialog(title: string | null, filterName: string | null, filterExtensions: string[]) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_file_dialog", { title, filterName, filterExtensions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareSilentUpdateAndRestart(downloadUrl: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_silent_update_and_restart", { downloadUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
backendEvent: BackendEvent
}>({
backendEvent: "backend-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AccountMetadata = { uuid: string; username: string; account_type: string; skin_url: string | null; cape_url: string | null; server_url: string | null; last_used_at: string; is_active: boolean }
export type AppErrorCode = "NO_DISK_SPACE" | "NETWORK_ERROR" | "HASH_MISMATCH" | "JAVA_NOT_FOUND" | "JAVA_INCOMPATIBLE" | "CLASSPATH_TOO_LONG" | "INVALID_MANIFEST" | "ZIP_SLIP_DETECTED" | "AUTH_FAILED" | "KEYRING_ACCESS_FAILED" | "ENCRYPTION_FAILED" | "DECRYPTION_FAILED" | "INSTANCE_NOT_FOUND" | "LAUNCH_PROVISION_FAILED" | "INTERNAL_ERROR"
export type BackendEvent = { type: "DownloadProgress"; data: { task_id: string; current: number; total: number; speed_bps: number; file_name: string } } | { type: "DownloadBatchProgress"; data: { items: DownloadProgressItem[] } } | { type: "DownloadCompleted"; data: { task_id: string } } | { type: "DownloadFailed"; data: { task_id: string; error_code: AppErrorCode; message: string } } | { type: "ProcessStarting"; data: { instance_id: string } } | { type: "ProcessStarted"; data: { instance_id: string; pid: number } } | { type: "ProcessLog"; data: { instance_id: string; line: string; is_stderr: boolean } } | { type: "ProcessLogBatch"; data: { instance_id: string; lines: string[] } } | { type: "ProcessExited"; data: { instance_id: string; exit_code: number | null } } | { type: "ProcessCrashed"; data: { instance_id: string; report: CrashReport } } | { type: "InstanceUpdated"; data: { instance_id: string } }
export type CrashPattern = "OutOfMemory" | { ClassNotFound: string } | { NoClassDefFound: string } | { UnsatisfiedLink: string } | { WrongJavaVersion: { expected: number; actual: number | null } } | "GpuDriverIssue" | { ModConflict: string } | "Unknown"
export type CrashReport = { pattern: CrashPattern; diagnosis: string; suggestion: string; full_log: string; exit_code: number | null; upload_url: string | null }
export type DependencyConflict = { mod_a: string; mod_b: string; reason: string }
export type DependencyType = "Required" | "Optional" | "Incompatible" | "Embedded"
export type DownloadProgressItem = { task_id: string; current: number; total: number; speed_bps: number; file_name: string }
export type EffectiveInstanceSettings = { java_path: string | null; memory_min_mb: number; memory_max_mb: number; gc_preset: string; jvm_args: string | null; has_overrides: boolean }
export type GlobalSettings = { theme: string; discord_rpc_enabled: boolean; update_channel: string; default_java_path: string | null; default_java_mode: string; default_java_provider: string; 
/**
 * @deprecated RAM allocation is exclusively configured per-instance
 */
default_memory_min_mb: number; 
/**
 * @deprecated RAM allocation is exclusively configured per-instance
 */
default_memory_max_mb: number; default_gc_preset: string; default_jvm_args: string | null }
export type InstalledMod = { id: string; name: string; version: string; file_name: string; enabled: boolean; description: string | null; authors: string[]; project_id: string | null }
export type InstalledRuntime = { major: number; path: string; provider: string; version_str: string }
export type Instance = { id: string; name: string; game_version: string; loader: string | null; loader_version: string | null; java_path: string | null; memory_min_mb: number | null; memory_max_mb: number | null; jvm_args: string | null; last_played_at: string | null; total_playtime_seconds: number; icon_path: string | null; banner_path: string | null; created_at: string; last_mclo_gs_url: string | null; last_mclo_gs_at: string | null; settings_json: string | null }
export type InstanceSettings = { java_path: string | null; memory_min_mb: number | null; memory_max_mb: number | null; gc_preset: string | null; jvm_args: string | null }
export type JavaInfo = { path: string; version: string; major: number; arch: string; vendor: string | null; is_system: boolean }
/**
 * Structured receipt representing synthesized launch parameters.
 */
export type LaunchReceipt = { java_path: string; working_dir: string; command: string; arguments: string[]; environment: Partial<{ [key in string]: string }>; classpath_tier: string; main_class: string; classpath: string[] }
export type MinecraftVersionEntry = { id: string; version_type: string; release_time: string }
export type ModDependency = { project_id: string | null; version_id: string | null; file_name: string | null; dependency_type: DependencyType }
export type ModFile = { url: string; filename: string; primary: boolean; size: number; hashes: ModFileHashes }
export type ModFileHashes = { sha1: string | null; sha512: string | null }
export type ModSearchResult = { project_id: string; slug: string; title: string; description: string; author: string; downloads: number; follows: number; icon_url: string | null; categories: string[]; versions: string[] }
export type ModUpdate = { project_id: string; current_version: string; latest_version: string; download_url: string }
export type ModVersion = { version_id: string; project_id: string; version_number: string; name: string; game_versions: string[]; loaders: string[]; files: ModFile[]; dependencies: ModDependency[]; date_published: string }
export type ModloaderType = "Fabric" | "NeoForge" | "Quilt" | "Forge"
export type ModloaderVersion = { loader: ModloaderType; version: string; game_version: string; stable: boolean }
export type ModpackInspectResult = { name: string; version: string; summary: string | null; game_version: string; loader: string; loader_version: string | null; file_count: number; author: string | null; icon_base64: string | null }
export type ModpackSearchResult = { provider: string; project_id: string; title: string; summary: string; author: string; downloads: number; icon_url: string | null; categories: string[]; latest_version: string | null; supported_game_versions: string[] }
export type ResolutionResult = { to_install: ModVersion[]; optional_suggestions: ModVersion[]; conflicts: DependencyConflict[] }
export type ResourcePackEntry = { file_name: string; name: string; description: string | null; icon_base64: string | null; is_enabled: boolean; size_bytes: number }
export type ShaderPackEntry = { file_name: string; name: string; is_active: boolean; size_bytes: number }
export type UpdateInfo = { version: string; date: string; body: string; download_size: number; download_url: string | null }
export type WorldEntry = { folder_name: string; level_name: string; seed: number | null; last_played: number | null; game_mode: string | null; size_bytes: number; icon_base64: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
