
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getLauncherVersion() : Promise<string> {
    return await TAURI_INVOKE("get_launcher_version");
},
async getOfflineUuid(username: string) : Promise<string> {
    return await TAURI_INVOKE("get_offline_uuid", { username });
},
async getInstances() : Promise<Result<Instance[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_instances") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLaunchReceipt(gameVersion: string, username: string) : Promise<Result<LaunchReceipt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_launch_receipt", { gameVersion, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchWithStubIdentity(gameVersion: string | null, memoryMaxMb: number | null) : Promise<Result<LaunchReceipt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_with_stub_identity", { gameVersion, memoryMaxMb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
backendEvent: BackendEvent
}>({
backendEvent: "backend-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppErrorCode = "NO_DISK_SPACE" | "NETWORK_ERROR" | "HASH_MISMATCH" | "JAVA_NOT_FOUND" | "JAVA_INCOMPATIBLE" | "CLASSPATH_TOO_LONG" | "INVALID_MANIFEST" | "ZIP_SLIP_DETECTED" | "AUTH_FAILED" | "INSTANCE_NOT_FOUND" | "INTERNAL_ERROR"
export type BackendEvent = { type: "DownloadProgress"; data: { task_id: string; current: number; total: number; speed_bps: number; file_name: string } } | { type: "DownloadBatchProgress"; data: { items: DownloadProgressItem[] } } | { type: "DownloadCompleted"; data: { task_id: string } } | { type: "DownloadFailed"; data: { task_id: string; error_code: AppErrorCode; message: string } } | { type: "ProcessStarting"; data: { instance_id: string } } | { type: "ProcessStarted"; data: { instance_id: string; pid: number } } | { type: "ProcessLog"; data: { instance_id: string; line: string; is_stderr: boolean } } | { type: "ProcessLogBatch"; data: { instance_id: string; lines: string[] } } | { type: "ProcessExited"; data: { instance_id: string; exit_code: number | null } } | { type: "InstanceUpdated"; data: { instance_id: string } }
export type DownloadProgressItem = { task_id: string; current: number; total: number; speed_bps: number; file_name: string }
export type Instance = { id: string; name: string; game_version: string; loader: string | null; loader_version: string | null; java_path: string | null; memory_min_mb: number | null; memory_max_mb: number | null; jvm_args: string | null; last_played_at: string | null; total_playtime_seconds: number; icon_path: string | null; banner_path: string | null; created_at: string }
/**
 * Structured receipt representing synthesized launch parameters.
 */
export type LaunchReceipt = { java_path: string; working_dir: string; command: string; arguments: string[]; environment: Partial<{ [key in string]: string }>; classpath_tier: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
